{"uuid": "0518d08d-f364-4454-80a0-1a6d514e3ea9", "children": ["d9f3fc56-ef8e-46b4-817a-c9dac4d1ce5c"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=115.0.5790.111)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0073A813+48355]\n\t(No symbol) [0x006CC4B1]\n\t(No symbol) [0x005D5358]\n\t(No symbol) [0x005D1B33]\n\t(No symbol) [0x005C8CA5]\n\t(No symbol) [0x005C9D0A]\n\t(No symbol) [0x005C9003]\n\t(No symbol) [0x005C8355]\n\t(No symbol) [0x005C82EC]\n\t(No symbol) [0x005C6F26]\n\t(No symbol) [0x005C7688]\n\t(No symbol) [0x005D6B52]\n\t(No symbol) [0x0062CF01]\n\t(No symbol) [0x0061A73C]\n\t(No symbol) [0x0062C922]\n\t(No symbol) [0x0061A536]\n\t(No symbol) [0x005F82DC]\n\t(No symbol) [0x005F93DD]\n\tGetHandleVerifier [0x0099AABD+2539405]\n\tGetHandleVerifier [0x009DA78F+2800735]\n\tGetHandleVerifier [0x009D456C+2775612]\n\tGetHandleVerifier [0x007C51E0+616112]\n\t(No symbol) [0x006D5F8C]\n\t(No symbol) [0x006D2328]\n\t(No symbol) [0x006D240B]\n\t(No symbol) [0x006C4FF7]\n\tBaseThreadInitThunk [0x76397D59+25]\n\tRtlInitializeExceptionChain [0x773CB79B+107]\n\tRtlClearBits [0x773CB71F+191]\n\n", "trace": "  File \"D:\\Cred_Kart_Project_Copy\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Kart_Project_Copy\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Kart_Project_Copy\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Kart_Project_Copy\\testCases\\conftest.py\", line 56, in setup\n    driver.get(\"https://automation.credence.in\")\n  File \"D:\\Cred_Kart_Project_Copy\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"D:\\Cred_Kart_Project_Copy\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Cred_Kart_Project_Copy\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691159599416, "stop": 1691159602064}], "start": 1691159599416, "stop": 1691159602279}